---
title: "posner"
author: "maki kiko minako"
date: "02/04/2020"
output: html_document
---
 We did Posner's classic gaze cuing experiment on psytoolkit.org. We recorded the results for us 3 participants, entered them into a csv file and tried to visualise them. 
 
```{r set up}
library(tidyverse)
```


```{r get data}
read_csv("posner.csv")
```
```{r read data}
posner_data <- read.csv("posner.csv")
```

```{r bar chart with count}
ggplot(posner_data, aes(x=type, fill= id)) + geom_bar(position = "dodge", alpha =.6)
```


```{r scatterplot}
ggplot(posner_data, aes(x=type, y= rt, color = id))+geom_point()+ scale_x_discrete(name="cue type (valid or invalid)") + scale_y_continuous(name="Reaction Time(msec)") + geom_smooth(method = lm)
```

```{r}
ggplot(posner_data, aes(x = type, y=rt, color=id)) + geom_boxplot() + geom_point() +geom_jitter(height = 0, width = .1) + scale_x_discrete(name="cue type (valid or invalid)") + scale_y_continuous(name="Reaction Time(msec)") + scale_fill_discrete(guide = FALSE)
```

```{r}
```


